# LibreLane configuration file

DESIGN_NAME: heichips25_tiny_wrapper2
VERILOG_FILES:
 - dir::../src/heichips25_tiny_wrapper2.sv
  # FSM
 - dir::../submodules/heichips25-fsm/src/Controller.v
 - dir::../submodules/heichips25-fsm/src/heichips25_can_lehmann_fsm.sv
 - dir::../submodules/heichips25-fsm/src/InstMem.v
  # SAP3
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/heichips25_sap3.sv
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/alu.v
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/array_serializer.sv
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/clk_div_param.sv
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/clock.v
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/controller.v
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/ir.v
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/reg_file.v
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/serializer.sv
 - dir::../submodules/heiChips2025_sap3_and_sorter/heichips25_sap-3/src/top.v

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true

FALLBACK_SDC_FILE: dir::../custom.sdc
